const styles = `<style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;background:#101217;color:#eef1f5;min-height:100vh}main{max-width:640px;margin:0 auto;padding:64px 24px}header{font-size:14px;color:#aeb7c5;letter-spacing:.08em;text-transform:uppercase}h1{font-size:clamp(34px,6vw,54px);line-height:1.08;margin:48px 0 18px}p{color:#b8c1cf;font-size:18px;line-height:1.55}button{border:0;border-radius:6px;background:#e9f4cb;color:#182118;padding:14px 22px;font-weight:700;font-size:16px;cursor:pointer}button:disabled{opacity:.55;cursor:wait}button:focus-visible,a:focus-visible{outline:3px solid #9fd2ff;outline-offset:3px}.panel{border-top:1px solid #39424f;margin-top:48px;padding-top:24px}.secondary{background:#2b333e;color:#fff;margin-left:8px}a{color:#b7ddff}code{display:block;overflow-wrap:anywhere;background:#232a32;border:1px solid #485363;border-radius:6px;padding:16px;margin:24px 0;color:#f0ffda}small{display:block;color:#9daabb;margin-top:32px}#message{min-height:28px}
</style>`;
const head = `<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>DayBoard license</title>`;
export const buyPage = (orderId: string) =>
  `<!doctype html><html lang="en"><head>${head}${styles}<script src="/buy.js" defer></script></head><body><main><header>DayBoard</header><h1>Make room for your day.</h1><p>Get an official DayBoard license for the macOS app. Checkout opens securely with Stripe.</p><div class="panel"><button id="buy" type="button" data-order-id="${orderId}">Continue to checkout</button><p id="message" role="status" aria-live="polite"></p></div><small>Your license is delivered on this device after payment. Keep the receipt page open to copy or download it.</small></main></body></html>`;
export const receiptPage = `<!doctype html><html lang="en"><head>${head}${styles}<script src="/receipt.js" defer></script></head><body><main><header>DayBoard</header><h1 id="title">Checking your order</h1><p id="message" role="status" aria-live="polite">Your payment may take a moment to confirm.</p><a id="retry" href="/buy" hidden>Start a new checkout</a><div id="license" class="panel" hidden><code id="key"></code><button id="copy" type="button">Copy license</button><button id="download" class="secondary" type="button">Download license</button></div><small>Keep your license in a safe place. If you lose access, contact support with your Stripe receipt for verified recovery.</small></main></body></html>`;
export const buyScript = `const button=document.getElementById('buy'),message=document.getElementById('message'),orderId=button.dataset.orderId;button.onclick=async()=>{button.disabled=true;message.textContent='Opening checkout…';try{const response=await fetch('/v1/checkout',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId})});const data=await response.json();if(!response.ok||!data.url)throw new Error();location.assign(data.url)}catch{message.textContent='Checkout is temporarily unavailable. Please try again.';button.disabled=false}};`;
export const receiptScript =
  `const title=document.getElementById('title'),message=document.getElementById('message'),box=document.getElementById('license'),key=document.getElementById('key'),orderId=new URL(location.href).searchParams.get('order');let licenseKey='';const show=(heading,text)=>{title.textContent=heading;message.textContent=text};async function poll(){if(!orderId||!%ORDER_PATTERN%.test(orderId)){show('Order access unavailable','Open the return link from your checkout or contact support with your Stripe receipt.');return}try{const response=await fetch('/v1/checkout/status?order='+encodeURIComponent(orderId),{credentials:'same-origin',cache:'no-store'});if(response.status===401){show('Order access unavailable','Open this page in the browser you used for checkout, or contact support with your Stripe receipt.');return}if(!response.ok)throw new Error();const status=await response.json();if(status.state==='pending'){show('Checking your order','Your payment may take a moment to confirm.');setTimeout(poll,2500);return}if(status.state==='revoked'){show('License unavailable','This payment was refunded or disputed. Contact support if you need help.');return}if(status.state==='failed'){show('Payment incomplete','No license was issued. Return to checkout to start a new order, or contact support.');document.getElementById('retry').hidden=false;return}const claim=await fetch('/v1/checkout/claim',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId})});if(!claim.ok)throw new Error();licenseKey=(await claim.json()).licenseKey;key.textContent=licenseKey;box.hidden=false;show('Your DayBoard license','Save your license, then enter it in the DayBoard app.')}catch{show('Still checking','The order could not be checked right now. Retrying…');setTimeout(poll,4000)}}poll();document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(licenseKey);message.textContent='License copied.'}catch{message.textContent='Copy is unavailable. Select the license above to copy it.'}};document.getElementById('download').onclick=()=>{const url=URL.createObjectURL(new Blob([licenseKey+'\\n'],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='dayboard-license.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};`.replace(
    "%ORDER_PATTERN%",
    "/^[A-Za-z0-9_-]{32}$/",
  );
